### ISSUE TITLE
Joining.

### ISSUE THREAD

**Issue by shadowdree** [2003tech/ProjectPheonix#1]
want to join

**Comment by shadowdree** [comment]
TABARNAK WHY NO ONE IS HERE

**Comment by PF94** [comment]
Added.

**Comment by PF94** [comment]
Please go to https://github.com/2003tech/ProjectPheonix/invitations.

**Comment by shadowdree** [comment]
Joined

**Comment by shadowdree** [comment]
hey I don't have my subsite

**Comment by EricZhang456** [comment]
Add it yourself

**Comment by PF94** [comment]
> 
> 
> hey I don't have my subsite

 Your Project Pheonix subsite looks the exact same thing as the one currently on RetroSite,
![image](https://user-images.githubusercontent.com/45898787/82155180-fb51ea80-9840-11ea-861c-87d2ea409f14.png)

However, the subsite originates from 2003page, which has a different "folder structure" compared to Project Pheonix. This causes a 404 error, as it was expecting the main page to be on ``2003page.ga/subsites/index.htm``, (2003page.ga is used as a placeholder until a proper name for Project Pheonix has been chosen.)
![image](https://user-images.githubusercontent.com/45898787/82155229-66032600-9841-11ea-8b52-f39fed0b5549.png)
(I haven't imported the one from 2003page yet)

I'd recommend making it a shortcut to your RetroSite subsite, or vice-versa.

**Comment by PF94** [comment]
I have made it a shortcut to http://retrosite.ga/shadow/index.htm.
