### ISSUE TITLE
Add Misc., Contributing Guide, etc

### ISSUE THREAD

**Issue by EricZhang456** [2003tech/ProjectPheonix#7]
Just like the part I commented out
```html
<!--
		<a href="/index.htm">Home</a>
		<br>
		<a href="/misc/index.htm">Misc. and Archived</a>
		<a href="/misc/compatibility/index.html">What works and what doesn't</a>
		<a href="https://github.com/2003tech/2003page.ga">Visit us on <br>GitHub</a>
		<a href="/misc/CONTRIBUTING/index.html">Contributing to 2003page</a>
	-->
```

**Comment by PF94** [comment]
Here's my idea:

1. Ditch the compatbility chart, it easily gets outdated.
2. Add a link to 2003discord 2.0
3. Keep everything else.
4. Don't implement "Misc. and Archived" until it's really needed.
5. For the contributing page, just make a file called contributing.html, without putting it on a random directory.

For the "Seal of Approval", which likely was meant to be listed there. I'm ditching that system. It was treated like a whitelist, and not a list of recommended software.

**Comment by EricZhang456** [comment]
should i delete the note?

**Comment by PF94** [comment]
Nah don't delete it.

**Comment by EricZhang456** [comment]
why not

**Comment by EricZhang456** [comment]
![图片](https://user-images.githubusercontent.com/32814750/82720036-72c0c780-9ce2-11ea-83e4-0d75c7efb174.png)
the navbar is too crowded

**Comment by Loogi-hub** [comment]
I TAKE IT ALL BACK THAT IS CROWDED

**Comment by PF94** [comment]
I don't have plans to add the remaining pages, maybe later once ProPheo gets more active...
